# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article_history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article_history.proto',
  package='common',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x61rticle_history.proto\x12\x06\x63ommon\"\xad\x01\n\x0e\x41rticleHistory\x12:\n\x08\x61rticles\x18\x01 \x03(\x0b\x32$.common.ArticleHistory.ArticlesEntryB\x02\x18\x01\x12\x16\n\narticleIds\x18\x02 \x03(\x04\x42\x02\x10\x01\x12\x16\n\ntimestamps\x18\x03 \x03(\x04\x42\x02\x10\x01\x1a/\n\rArticlesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x42%\n#com.smartnews.ad.dmp.common.articleb\x06proto3')
)




_ARTICLEHISTORY_ARTICLESENTRY = _descriptor.Descriptor(
  name='ArticlesEntry',
  full_name='common.ArticleHistory.ArticlesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='common.ArticleHistory.ArticlesEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.ArticleHistory.ArticlesEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=207,
)

_ARTICLEHISTORY = _descriptor.Descriptor(
  name='ArticleHistory',
  full_name='common.ArticleHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='articles', full_name='common.ArticleHistory.articles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='articleIds', full_name='common.ArticleHistory.articleIds', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='common.ArticleHistory.timestamps', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[_ARTICLEHISTORY_ARTICLESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=207,
)

_ARTICLEHISTORY_ARTICLESENTRY.containing_type = _ARTICLEHISTORY
_ARTICLEHISTORY.fields_by_name['articles'].message_type = _ARTICLEHISTORY_ARTICLESENTRY
DESCRIPTOR.message_types_by_name['ArticleHistory'] = _ARTICLEHISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArticleHistory = _reflection.GeneratedProtocolMessageType('ArticleHistory', (_message.Message,), dict(

  ArticlesEntry = _reflection.GeneratedProtocolMessageType('ArticlesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ARTICLEHISTORY_ARTICLESENTRY,
    __module__ = 'article_history_pb2'
    # @@protoc_insertion_point(class_scope:common.ArticleHistory.ArticlesEntry)
    ))
  ,
  DESCRIPTOR = _ARTICLEHISTORY,
  __module__ = 'article_history_pb2'
  # @@protoc_insertion_point(class_scope:common.ArticleHistory)
  ))
_sym_db.RegisterMessage(ArticleHistory)
_sym_db.RegisterMessage(ArticleHistory.ArticlesEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.smartnews.ad.dmp.common.article'))
_ARTICLEHISTORY_ARTICLESENTRY.has_options = True
_ARTICLEHISTORY_ARTICLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_ARTICLEHISTORY.fields_by_name['articles'].has_options = True
_ARTICLEHISTORY.fields_by_name['articles']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_ARTICLEHISTORY.fields_by_name['articleIds'].has_options = True
_ARTICLEHISTORY.fields_by_name['articleIds']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_ARTICLEHISTORY.fields_by_name['timestamps'].has_options = True
_ARTICLEHISTORY.fields_by_name['timestamps']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
