# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: w2v.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='w2v.proto',
  package='com.smartnews.nlp.w2v',
  syntax='proto3',
  serialized_pb=_b('\n\tw2v.proto\x12\x15\x63om.smartnews.nlp.w2v\"h\n\x05Vocab\x12\x0b\n\x03idx\x18\x01 \x01(\r\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x0b\n\x03\x63nt\x18\x03 \x01(\r\x12\x10\n\x04\x63ode\x18\x04 \x03(\rB\x02\x10\x01\x12\x11\n\x05point\x18\x05 \x03(\rB\x02\x10\x01\x12\x12\n\x06vector\x18\x06 \x03(\x02\x42\x02\x10\x01\":\n\nMultiVocab\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x1c.com.smartnews.nlp.w2v.Vocab\"\"\n\x0c\x44oubleVector\x12\x12\n\x06points\x18\x01 \x03(\x01\x42\x02\x10\x01\"H\n\x11MultiDoubleVector\x12\x33\n\x06values\x18\x01 \x03(\x0b\x32#.com.smartnews.nlp.w2v.DoubleVector\"!\n\x0b\x46loatVector\x12\x12\n\x06points\x18\x01 \x03(\x02\x42\x02\x10\x01\"F\n\x10MultiFloatVector\x12\x32\n\x06values\x18\x01 \x03(\x0b\x32\".com.smartnews.nlp.w2v.FloatVectorb\x06proto3')
)




_VOCAB = _descriptor.Descriptor(
  name='Vocab',
  full_name='com.smartnews.nlp.w2v.Vocab',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='com.smartnews.nlp.w2v.Vocab.idx', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word', full_name='com.smartnews.nlp.w2v.Vocab.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cnt', full_name='com.smartnews.nlp.w2v.Vocab.cnt', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='com.smartnews.nlp.w2v.Vocab.code', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='point', full_name='com.smartnews.nlp.w2v.Vocab.point', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='vector', full_name='com.smartnews.nlp.w2v.Vocab.vector', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=140,
)


_MULTIVOCAB = _descriptor.Descriptor(
  name='MultiVocab',
  full_name='com.smartnews.nlp.w2v.MultiVocab',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='com.smartnews.nlp.w2v.MultiVocab.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=200,
)


_DOUBLEVECTOR = _descriptor.Descriptor(
  name='DoubleVector',
  full_name='com.smartnews.nlp.w2v.DoubleVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='com.smartnews.nlp.w2v.DoubleVector.points', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=236,
)


_MULTIDOUBLEVECTOR = _descriptor.Descriptor(
  name='MultiDoubleVector',
  full_name='com.smartnews.nlp.w2v.MultiDoubleVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='com.smartnews.nlp.w2v.MultiDoubleVector.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=310,
)


_FLOATVECTOR = _descriptor.Descriptor(
  name='FloatVector',
  full_name='com.smartnews.nlp.w2v.FloatVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='com.smartnews.nlp.w2v.FloatVector.points', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=345,
)


_MULTIFLOATVECTOR = _descriptor.Descriptor(
  name='MultiFloatVector',
  full_name='com.smartnews.nlp.w2v.MultiFloatVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='com.smartnews.nlp.w2v.MultiFloatVector.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=417,
)

_MULTIVOCAB.fields_by_name['values'].message_type = _VOCAB
_MULTIDOUBLEVECTOR.fields_by_name['values'].message_type = _DOUBLEVECTOR
_MULTIFLOATVECTOR.fields_by_name['values'].message_type = _FLOATVECTOR
DESCRIPTOR.message_types_by_name['Vocab'] = _VOCAB
DESCRIPTOR.message_types_by_name['MultiVocab'] = _MULTIVOCAB
DESCRIPTOR.message_types_by_name['DoubleVector'] = _DOUBLEVECTOR
DESCRIPTOR.message_types_by_name['MultiDoubleVector'] = _MULTIDOUBLEVECTOR
DESCRIPTOR.message_types_by_name['FloatVector'] = _FLOATVECTOR
DESCRIPTOR.message_types_by_name['MultiFloatVector'] = _MULTIFLOATVECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vocab = _reflection.GeneratedProtocolMessageType('Vocab', (_message.Message,), dict(
  DESCRIPTOR = _VOCAB,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.Vocab)
  ))
_sym_db.RegisterMessage(Vocab)

MultiVocab = _reflection.GeneratedProtocolMessageType('MultiVocab', (_message.Message,), dict(
  DESCRIPTOR = _MULTIVOCAB,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.MultiVocab)
  ))
_sym_db.RegisterMessage(MultiVocab)

DoubleVector = _reflection.GeneratedProtocolMessageType('DoubleVector', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLEVECTOR,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.DoubleVector)
  ))
_sym_db.RegisterMessage(DoubleVector)

MultiDoubleVector = _reflection.GeneratedProtocolMessageType('MultiDoubleVector', (_message.Message,), dict(
  DESCRIPTOR = _MULTIDOUBLEVECTOR,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.MultiDoubleVector)
  ))
_sym_db.RegisterMessage(MultiDoubleVector)

FloatVector = _reflection.GeneratedProtocolMessageType('FloatVector', (_message.Message,), dict(
  DESCRIPTOR = _FLOATVECTOR,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.FloatVector)
  ))
_sym_db.RegisterMessage(FloatVector)

MultiFloatVector = _reflection.GeneratedProtocolMessageType('MultiFloatVector', (_message.Message,), dict(
  DESCRIPTOR = _MULTIFLOATVECTOR,
  __module__ = 'w2v_pb2'
  # @@protoc_insertion_point(class_scope:com.smartnews.nlp.w2v.MultiFloatVector)
  ))
_sym_db.RegisterMessage(MultiFloatVector)


_VOCAB.fields_by_name['code'].has_options = True
_VOCAB.fields_by_name['code']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_VOCAB.fields_by_name['point'].has_options = True
_VOCAB.fields_by_name['point']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_VOCAB.fields_by_name['vector'].has_options = True
_VOCAB.fields_by_name['vector']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_DOUBLEVECTOR.fields_by_name['points'].has_options = True
_DOUBLEVECTOR.fields_by_name['points']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_FLOATVECTOR.fields_by_name['points'].has_options = True
_FLOATVECTOR.fields_by_name['points']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
